name: haskell-macos-14

on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  haskell-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}

    steps:

    - name: Install LLVM 12
      run: |
        brew install llvm@12
        echo "$(brew --prefix)/opt/llvm/bin"                >> "${GITHUB_PATH}"
        echo LDFLAGS="-L$(brew --prefix)/opt/llvm/lib"      >> "${GITHUB_ENV}"
        echo CPPFLAGS="-I$(brew --prefix)/opt/llvm/include" >> "${GITHUB_ENV}"
      # echo "LDFLAGS=-L$(brew --prefix)/opt/llvm/lib/c++ -Wl,-rpath,$(brew --prefix)/opt/llvm/lib/c++" >> "${GITHUB_ENV}"

    - uses: haskell-actions/setup@latest
      with:
        ghc-version: '8.10'

    - run: cabal install alex
